// <auto-generated />
using System;
using EduConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduConnect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251111145103_fixlophoc")]
    partial class fixlophoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduConnect.Models.DatLaiMatKhau", b =>
                {
                    b.Property<Guid>("MaDatLaiMatKhau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maDatLaiMatKhau");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("hetHanLuc");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maNguoiDung");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("token");

                    b.Property<bool>("Used")
                        .HasColumnType("bit")
                        .HasColumnName("daSuDung");

                    b.HasKey("MaDatLaiMatKhau");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DATLAIMATKHAU");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.BaiLamChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("DungSai")
                        .HasColumnType("bit")
                        .HasColumnName("dungSai");

                    b.Property<int>("MaBaiLam")
                        .HasColumnType("int")
                        .HasColumnName("maBaiLam");

                    b.Property<int>("MaCauHoi")
                        .HasColumnType("int")
                        .HasColumnName("maCauHoi");

                    b.Property<string>("TraLoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("traLoi");

                    b.HasKey("Id");

                    b.HasIndex("MaBaiLam");

                    b.HasIndex("MaCauHoi");

                    b.ToTable("BAILAMCHITIET");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.BaiLamHocLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Diem")
                        .HasColumnType("float")
                        .HasColumnName("diem");

                    b.Property<int>("HocLieuId")
                        .HasColumnType("int")
                        .HasColumnName("hocLieuId");

                    b.Property<int>("HocSinhId")
                        .HasColumnType("int")
                        .HasColumnName("hocSinhId");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayBatDau");

                    b.Property<DateTime?>("NgayNop")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayNop");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trangThai");

                    b.HasKey("Id");

                    b.HasIndex("HocLieuId");

                    b.HasIndex("HocSinhId");

                    b.ToTable("BAILAMHOCLIEU");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.CauHoiHocLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DapAnA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnDung")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("DoKho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HocLieuId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiCauHoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HocLieuId");

                    b.ToTable("CauHoiHocLieus");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.HocLieu", b =>
                {
                    b.Property<int>("HocLieuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hocLieuId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HocLieuId"));

                    b.Property<int?>("KhoaHocId")
                        .HasColumnType("int")
                        .HasColumnName("khoaHocId");

                    b.Property<bool>("LaHocLieuAn")
                        .HasColumnType("bit")
                        .HasColumnName("laHocLieuAn");

                    b.Property<bool>("LaHocLieuTuDo")
                        .HasColumnType("bit")
                        .HasColumnName("laHocLieuTuDo");

                    b.Property<string>("MaLoaiHocLieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maLoaiHocLieu");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao");

                    b.Property<Guid>("NguoiTaoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("nguoiTaoId");

                    b.Property<string>("NguonTao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nguonTao");

                    b.Property<string>("TenHocLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenHocLieu");

                    b.Property<string>("TenKhoaHoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenKhoaHoc");

                    b.Property<string>("TenLoaiHocLieu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenLoaiHocLieu");

                    b.HasKey("HocLieuId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("HOCLIEU");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.HocLieuCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CauHoiId")
                        .HasColumnType("int");

                    b.Property<int>("HocLieuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiId");

                    b.HasIndex("HocLieuId");

                    b.ToTable("HocLieuCauHois");
                });

            modelBuilder.Entity("EduConnect.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLopHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maLopHoc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLopHoc"));

                    b.Property<int>("MaKhoiHoc")
                        .HasColumnType("int")
                        .HasColumnName("maKhoiHoc");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("nguoiTaoId");

                    b.Property<int?>("SiSo")
                        .HasColumnType("int")
                        .HasColumnName("siSo");

                    b.Property<string>("TenLopHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("tenLopHoc");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaLopHoc");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("MaKhoiHoc", "TenLopHoc")
                        .IsUnique();

                    b.ToTable("LOPHOC");
                });

            modelBuilder.Entity("EduConnect.Models.NguoiDung", b =>
                {
                    b.Property<Guid>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maNguoiDung");

                    b.Property<string>("AnhDaiDien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasDefaultValue("/template/img/avt.svg")
                        .HasColumnName("anhDaiDien");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int?>("GiaoVienMaGiaoVien")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hoTen");

                    b.Property<int?>("HocSinhMaHocSinh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2")
                        .HasColumnName("lanDangNhapCuoi");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("matKhauHash");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao");

                    b.Property<string>("NguonXacThuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nguonXacThuc");

                    b.Property<bool>("PhaiDoiMatKhau")
                        .HasColumnType("bit")
                        .HasColumnName("phaiDoiMatKhau");

                    b.Property<int?>("PhuHuynhMaPhuHuynh")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("soDienThoai");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenDangNhap");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("vaiTro");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("GiaoVienMaGiaoVien");

                    b.HasIndex("HocSinhMaHocSinh");

                    b.HasIndex("PhuHuynhMaPhuHuynh");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NGUOIDUNG");
                });

            modelBuilder.Entity("EduConnect.Models.School.KhoiHoc", b =>
                {
                    b.Property<int>("MaKhoiHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maKhoiHoc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoiHoc"));

                    b.Property<string>("TenKhoiHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenKhoiHoc");

                    b.HasKey("MaKhoiHoc");

                    b.ToTable("KHOIHOC");

                    b.HasData(
                        new
                        {
                            MaKhoiHoc = 10,
                            TenKhoiHoc = "Khối 10"
                        },
                        new
                        {
                            MaKhoiHoc = 11,
                            TenKhoiHoc = "Khối 11"
                        },
                        new
                        {
                            MaKhoiHoc = 12,
                            TenKhoiHoc = "Khối 12"
                        });
                });

            modelBuilder.Entity("EduConnect.Models.School.LienKetPhuHuynhHocSinh", b =>
                {
                    b.Property<int>("MaLienKet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maLienKet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLienKet"));

                    b.Property<int>("MaHocSinh")
                        .HasColumnType("int")
                        .HasColumnName("maHocSinh");

                    b.Property<int>("MaPhuHuynh")
                        .HasColumnType("int")
                        .HasColumnName("maPhuHuynh");

                    b.Property<string>("MoiQuanHe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("moiQuanHe");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trangThai");

                    b.HasKey("MaLienKet");

                    b.HasIndex("MaHocSinh");

                    b.HasIndex("MaPhuHuynh");

                    b.ToTable("LIENKET_PHUHUYNH_HOCSINH");
                });

            modelBuilder.Entity("EduConnect.Models.TokenLamMoi", b =>
                {
                    b.Property<Guid>("MaTokenLamMoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maTokenLamMoi");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("hetHanLuc");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maNguoiDung");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("biHuyLuc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("token");

                    b.HasKey("MaTokenLamMoi");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("TOKENLAMMOI");
                });

            modelBuilder.Entity("GiaoVien", b =>
                {
                    b.Property<int>("MaGiaoVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maGiaoVien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoVien"));

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("chuyenMon");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maNguoiDung");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayBatDau");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao");

                    b.Property<bool>("TrangThaiCongTac")
                        .HasColumnType("bit")
                        .HasColumnName("trangThaiCongTac");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("trinhDo");

                    b.HasKey("MaGiaoVien");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("GIAOVIEN");
                });

            modelBuilder.Entity("HocSinh", b =>
                {
                    b.Property<int>("MaHocSinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maHocSinh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocSinh"));

                    b.Property<bool>("LaLopTruong")
                        .HasColumnType("bit")
                        .HasColumnName("laLopTruong");

                    b.Property<string>("MaDinhDanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maDinhDanh");

                    b.Property<int?>("MaLopHoc")
                        .HasColumnType("int")
                        .HasColumnName("maLopHoc");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maNguoiDung");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaySinh");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao");

                    b.HasKey("MaHocSinh");

                    b.HasIndex("MaLopHoc");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("HOCSINH");
                });

            modelBuilder.Entity("PhuHuynh", b =>
                {
                    b.Property<int>("MaPhuHuynh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maPhuHuynh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuHuynh"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maNguoiDung");

                    b.Property<string>("MucDoLienKet")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mucDoLienKet");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao");

                    b.Property<string>("NgheNghiep")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ngheNghiep");

                    b.HasKey("MaPhuHuynh");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("PHUHUYNH");
                });

            modelBuilder.Entity("XacThucEmail", b =>
                {
                    b.Property<Guid>("MaXacThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maXacThuc");

                    b.Property<bool>("DaSuDung")
                        .HasColumnType("bit")
                        .HasColumnName("daSuDung");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("maCode");

                    b.Property<Guid>("MaNguoiDung")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maNguoiDung");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayHetHan");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao");

                    b.HasKey("MaXacThuc");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("XACTHUCEMAIL");
                });

            modelBuilder.Entity("EduConnect.Models.DatLaiMatKhau", b =>
                {
                    b.HasOne("EduConnect.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.BaiLamChiTiet", b =>
                {
                    b.HasOne("EduConnect.Models.HocLieu.BaiLamHocLieu", "BaiLamHocLieu")
                        .WithMany("ChiTiets")
                        .HasForeignKey("MaBaiLam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduConnect.Models.HocLieu.CauHoiHocLieu", "CauHoiHocLieu")
                        .WithMany()
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiLamHocLieu");

                    b.Navigation("CauHoiHocLieu");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.BaiLamHocLieu", b =>
                {
                    b.HasOne("EduConnect.Models.HocLieu.HocLieu", "HocLieu")
                        .WithMany("BaiLams")
                        .HasForeignKey("HocLieuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HocSinh", "HocSinh")
                        .WithMany()
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocLieu");

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.CauHoiHocLieu", b =>
                {
                    b.HasOne("EduConnect.Models.HocLieu.HocLieu", "HocLieu")
                        .WithMany("CauHois")
                        .HasForeignKey("HocLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocLieu");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.HocLieu", b =>
                {
                    b.HasOne("EduConnect.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.HocLieuCauHoi", b =>
                {
                    b.HasOne("EduConnect.Models.HocLieu.CauHoiHocLieu", "CauHoi")
                        .WithMany()
                        .HasForeignKey("CauHoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduConnect.Models.HocLieu.HocLieu", "HocLieu")
                        .WithMany("HocLieuCauHois")
                        .HasForeignKey("HocLieuId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("HocLieu");
                });

            modelBuilder.Entity("EduConnect.Models.LopHoc", b =>
                {
                    b.HasOne("EduConnect.Models.School.KhoiHoc", "KhoiHoc")
                        .WithMany("LopHocs")
                        .HasForeignKey("MaKhoiHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduConnect.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhoiHoc");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("EduConnect.Models.NguoiDung", b =>
                {
                    b.HasOne("GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("GiaoVienMaGiaoVien");

                    b.HasOne("HocSinh", "HocSinh")
                        .WithMany()
                        .HasForeignKey("HocSinhMaHocSinh");

                    b.HasOne("PhuHuynh", "PhuHuynh")
                        .WithMany()
                        .HasForeignKey("PhuHuynhMaPhuHuynh");

                    b.Navigation("GiaoVien");

                    b.Navigation("HocSinh");

                    b.Navigation("PhuHuynh");
                });

            modelBuilder.Entity("EduConnect.Models.School.LienKetPhuHuynhHocSinh", b =>
                {
                    b.HasOne("HocSinh", "HocSinh")
                        .WithMany()
                        .HasForeignKey("MaHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhuHuynh", "PhuHuynh")
                        .WithMany("LienKetPhuHuynhHocSinhs")
                        .HasForeignKey("MaPhuHuynh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("PhuHuynh");
                });

            modelBuilder.Entity("EduConnect.Models.TokenLamMoi", b =>
                {
                    b.HasOne("EduConnect.Models.NguoiDung", "NguoiDung")
                        .WithMany("TokenLamMois")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GiaoVien", b =>
                {
                    b.HasOne("EduConnect.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("HocSinh", b =>
                {
                    b.HasOne("EduConnect.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EduConnect.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("PhuHuynh", b =>
                {
                    b.HasOne("EduConnect.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("XacThucEmail", b =>
                {
                    b.HasOne("EduConnect.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.BaiLamHocLieu", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.HocLieu", b =>
                {
                    b.Navigation("BaiLams");

                    b.Navigation("CauHois");

                    b.Navigation("HocLieuCauHois");
                });

            modelBuilder.Entity("EduConnect.Models.NguoiDung", b =>
                {
                    b.Navigation("TokenLamMois");
                });

            modelBuilder.Entity("EduConnect.Models.School.KhoiHoc", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("PhuHuynh", b =>
                {
                    b.Navigation("LienKetPhuHuynhHocSinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
