// <auto-generated />
using System;
using EduConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduConnect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251102181217_CreateHocLieuTable")]
    partial class CreateHocLieuTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduConnect.Models.Auth.EmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("EduConnect.Models.Auth.PasswordReset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("EduConnect.Models.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EduConnect.Models.Auth.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EduConnect.Models.HocLieu.HocLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<bool>("LaHocLieuAn")
                        .HasColumnType("bit");

                    b.Property<bool>("LaHocLieuTuDo")
                        .HasColumnType("bit");

                    b.Property<string>("MaLoaiHocLieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguonTao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenHocLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoaiHocLieu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("HocLieu");
                });

            modelBuilder.Entity("EduConnect.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLopHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maLopHoc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLopHoc"));

                    b.Property<int?>("GiaoVienMaGiaoVien")
                        .HasColumnType("int");

                    b.Property<int?>("KhoiHocMaKhoiHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoiHoc")
                        .HasColumnType("int")
                        .HasColumnName("maKhoiHoc");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao");

                    b.Property<int?>("SiSo")
                        .HasColumnType("int")
                        .HasColumnName("siSo");

                    b.Property<string>("TenLopHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tenLopHoc");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaLopHoc");

                    b.HasIndex("GiaoVienMaGiaoVien");

                    b.HasIndex("KhoiHocMaKhoiHoc");

                    b.HasIndex("MaKhoiHoc");

                    b.ToTable("LOPHOC");
                });

            modelBuilder.Entity("EduConnect.Models.School.GiaoVien", b =>
                {
                    b.Property<int>("MaGiaoVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maGiaoVien");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoVien"));

                    b.Property<string>("ChuyenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("chuyenMon");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("maNguoiDung");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayBatDau");

                    b.Property<bool>("TrangThaiCongTac")
                        .HasColumnType("bit")
                        .HasColumnName("trangThaiCongTac");

                    b.Property<string>("TrinhDo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("trinhDo");

                    b.HasKey("MaGiaoVien");

                    b.ToTable("GIAOVIEN");
                });

            modelBuilder.Entity("EduConnect.Models.School.HocSinh", b =>
                {
                    b.Property<int>("MaHocSinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maHocSinh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocSinh"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gioiTinh");

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int")
                        .HasColumnName("maLopHoc");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("maNguoiDung");

                    b.Property<DateTime?>("NgayNhapHoc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayNhapHoc");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaySinh");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaHocSinh");

                    b.HasIndex("MaLopHoc");

                    b.ToTable("HOCSINH");
                });

            modelBuilder.Entity("EduConnect.Models.School.KhoiHoc", b =>
                {
                    b.Property<int>("MaKhoiHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maKhoiHoc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoiHoc"));

                    b.Property<string>("TenKhoiHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenKhoiHoc");

                    b.HasKey("MaKhoiHoc");

                    b.ToTable("KHOIHOC");

                    b.HasData(
                        new
                        {
                            MaKhoiHoc = 10,
                            TenKhoiHoc = "Khối 10"
                        },
                        new
                        {
                            MaKhoiHoc = 11,
                            TenKhoiHoc = "Khối 11"
                        },
                        new
                        {
                            MaKhoiHoc = 12,
                            TenKhoiHoc = "Khối 12"
                        });
                });

            modelBuilder.Entity("EduConnect.Models.School.LienKetPhuHuynhHocSinh", b =>
                {
                    b.Property<int>("MaLienKet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maLienKet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLienKet"));

                    b.Property<int>("MaHocSinh")
                        .HasColumnType("int")
                        .HasColumnName("maHocSinh");

                    b.Property<int>("MaPhuHuynh")
                        .HasColumnType("int")
                        .HasColumnName("maPhuHuynh");

                    b.Property<string>("MoiQuanHe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("moiQuanHe");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trangThai");

                    b.HasKey("MaLienKet");

                    b.HasIndex("MaHocSinh");

                    b.HasIndex("MaPhuHuynh");

                    b.ToTable("LIENKET_PHUHUYNH_HOCSINH");
                });

            modelBuilder.Entity("EduConnect.Models.School.PhuHuynh", b =>
                {
                    b.Property<int>("MaPhuHuynh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maPhuHuynh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuHuynh"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("maNguoiDung");

                    b.Property<string>("MucDoLienKet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mucDoLienKet");

                    b.Property<string>("NgheNghiep")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ngheNghiep");

                    b.HasKey("MaPhuHuynh");

                    b.ToTable("PHUHUYNH");
                });

            modelBuilder.Entity("EduConnect.Models.Auth.EmailVerification", b =>
                {
                    b.HasOne("EduConnect.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduConnect.Models.Auth.PasswordReset", b =>
                {
                    b.HasOne("EduConnect.Models.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduConnect.Models.Auth.RefreshToken", b =>
                {
                    b.HasOne("EduConnect.Models.Auth.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduConnect.Models.LopHoc", b =>
                {
                    b.HasOne("EduConnect.Models.School.GiaoVien", null)
                        .WithMany("LopHocsChuNhiem")
                        .HasForeignKey("GiaoVienMaGiaoVien");

                    b.HasOne("EduConnect.Models.School.KhoiHoc", null)
                        .WithMany("LopHocs")
                        .HasForeignKey("KhoiHocMaKhoiHoc");

                    b.HasOne("EduConnect.Models.School.KhoiHoc", "KhoiHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoiHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoiHoc");
                });

            modelBuilder.Entity("EduConnect.Models.School.HocSinh", b =>
                {
                    b.HasOne("EduConnect.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("EduConnect.Models.School.LienKetPhuHuynhHocSinh", b =>
                {
                    b.HasOne("EduConnect.Models.School.HocSinh", "HocSinh")
                        .WithMany("LienKetPhuHuynhHocSinhs")
                        .HasForeignKey("MaHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduConnect.Models.School.PhuHuynh", "PhuHuynh")
                        .WithMany("LienKetPhuHuynhHocSinhs")
                        .HasForeignKey("MaPhuHuynh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("PhuHuynh");
                });

            modelBuilder.Entity("EduConnect.Models.Auth.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("EduConnect.Models.School.GiaoVien", b =>
                {
                    b.Navigation("LopHocsChuNhiem");
                });

            modelBuilder.Entity("EduConnect.Models.School.HocSinh", b =>
                {
                    b.Navigation("LienKetPhuHuynhHocSinhs");
                });

            modelBuilder.Entity("EduConnect.Models.School.KhoiHoc", b =>
                {
                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("EduConnect.Models.School.PhuHuynh", b =>
                {
                    b.Navigation("LienKetPhuHuynhHocSinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
