// <auto-generated />
using System;
using EduConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduConnect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251026062004_AddEmailAndPasswordReset")]
    partial class AddEmailAndPasswordReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduConnect.Models.BaiLamTracNghiem", b =>
                {
                    b.Property<int>("MaBaiLam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maBaiLam");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiLam"));

                    b.Property<decimal>("DiemSo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("diemSo");

                    b.Property<int>("MaHocSinh")
                        .HasColumnType("int")
                        .HasColumnName("maHocSinh");

                    b.Property<int>("MaTracNghiem")
                        .HasColumnType("int")
                        .HasColumnName("maTracNghiem");

                    b.Property<int>("SoCauDung")
                        .HasColumnType("int")
                        .HasColumnName("soCauDung");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoiGianBatDau");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoiGianKetThuc");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trangThai");

                    b.HasKey("MaBaiLam");

                    b.ToTable("BAILAM_TRACNGHIEM");
                });

            modelBuilder.Entity("EduConnect.Models.CauHoi", b =>
                {
                    b.Property<int>("MaCauHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maCauHoi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHoi"));

                    b.Property<string>("ChuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chuDe");

                    b.Property<decimal>("DiemDoiDa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("diemDoiDa");

                    b.Property<string>("DoKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("doKho");

                    b.Property<int>("MaKhoiHoc")
                        .HasColumnType("int")
                        .HasColumnName("maKhoiHoc");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int")
                        .HasColumnName("maMonHoc");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDung");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int")
                        .HasColumnName("thuTu");

                    b.HasKey("MaCauHoi");

                    b.ToTable("CAUHOI");
                });

            modelBuilder.Entity("EduConnect.Models.ChiTietTraLoi", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maChiTiet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal?>("DiemDatDuoc")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("diemDatDuoc");

                    b.Property<bool?>("IsDung")
                        .HasColumnType("bit")
                        .HasColumnName("isDung");

                    b.Property<int>("MaBaiLam")
                        .HasColumnType("int")
                        .HasColumnName("maBaiLam");

                    b.Property<int>("MaCauHoi")
                        .HasColumnType("int")
                        .HasColumnName("maCauHoi");

                    b.Property<int?>("MaDapAnChon")
                        .HasColumnType("int")
                        .HasColumnName("maDapAnChon");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaBaiLam");

                    b.HasIndex("MaCauHoi");

                    b.ToTable("CHITIET_TRALOI");
                });

            modelBuilder.Entity("EduConnect.Models.DapAn", b =>
                {
                    b.Property<int>("MaDapAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maDapAn");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDapAn"));

                    b.Property<bool>("LaDapAnDung")
                        .HasColumnType("bit")
                        .HasColumnName("laDapAnDung");

                    b.Property<int>("MaCauHoi")
                        .HasColumnType("int")
                        .HasColumnName("maCauHoi");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDung");

                    b.HasKey("MaDapAn");

                    b.HasIndex("MaCauHoi");

                    b.ToTable("DAPAN");
                });

            modelBuilder.Entity("EduConnect.Models.EmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("EduConnect.Models.GoiYHocTap", b =>
                {
                    b.Property<int>("MaGoiY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maGoiY");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGoiY"));

                    b.Property<string>("DuongDanTaiLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duongDanTaiLieu");

                    b.Property<int>("MaGoiYHocTap")
                        .HasColumnType("int")
                        .HasColumnName("maGoiYHocTap");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int")
                        .HasColumnName("maMonHoc");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.Property<string>("NoiDungGoiY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDungGoiY");

                    b.HasKey("MaGoiY");

                    b.ToTable("GOIY_HOCTAP");
                });

            modelBuilder.Entity("EduConnect.Models.PasswordReset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("EduConnect.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EduConnect.Models.TracNghiem", b =>
                {
                    b.Property<int>("MaTracNghiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maTracNghiem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTracNghiem"));

                    b.Property<string>("ChuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chuDe");

                    b.Property<string>("DoKho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("doKho");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao");

                    b.Property<int>("SoLuongCauHoi")
                        .HasColumnType("int")
                        .HasColumnName("soLuongCauHoi");

                    b.Property<string>("TenDeThi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tenDeThi");

                    b.HasKey("MaTracNghiem");

                    b.ToTable("TRACNGHIEM");
                });

            modelBuilder.Entity("EduConnect.Models.TracNghiemCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaCauHoi")
                        .HasColumnType("int")
                        .HasColumnName("maCauHoi");

                    b.Property<int>("MaTracNghiem")
                        .HasColumnType("int")
                        .HasColumnName("maTracNghiem");

                    b.HasKey("Id");

                    b.HasIndex("MaCauHoi");

                    b.HasIndex("MaTracNghiem");

                    b.ToTable("TRACNGHIEM_CAUHOI");
                });

            modelBuilder.Entity("EduConnect.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EduConnect.Models.ChiTietTraLoi", b =>
                {
                    b.HasOne("EduConnect.Models.BaiLamTracNghiem", "BaiLamTracNghiem")
                        .WithMany("ChiTietTraLois")
                        .HasForeignKey("MaBaiLam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduConnect.Models.CauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiLamTracNghiem");

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("EduConnect.Models.DapAn", b =>
                {
                    b.HasOne("EduConnect.Models.CauHoi", "CauHoi")
                        .WithMany("DapAns")
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");
                });

            modelBuilder.Entity("EduConnect.Models.EmailVerification", b =>
                {
                    b.HasOne("EduConnect.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduConnect.Models.PasswordReset", b =>
                {
                    b.HasOne("EduConnect.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduConnect.Models.RefreshToken", b =>
                {
                    b.HasOne("EduConnect.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduConnect.Models.TracNghiemCauHoi", b =>
                {
                    b.HasOne("EduConnect.Models.CauHoi", "CauHoi")
                        .WithMany()
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduConnect.Models.TracNghiem", "TracNghiem")
                        .WithMany("TracNghiemCauHois")
                        .HasForeignKey("MaTracNghiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauHoi");

                    b.Navigation("TracNghiem");
                });

            modelBuilder.Entity("EduConnect.Models.BaiLamTracNghiem", b =>
                {
                    b.Navigation("ChiTietTraLois");
                });

            modelBuilder.Entity("EduConnect.Models.CauHoi", b =>
                {
                    b.Navigation("DapAns");
                });

            modelBuilder.Entity("EduConnect.Models.TracNghiem", b =>
                {
                    b.Navigation("TracNghiemCauHois");
                });

            modelBuilder.Entity("EduConnect.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
